# Generated by Django 2.1 on 2019-03-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('given_date', models.DateTimeField(auto_now_add=True)),
                ('paid_date', models.DateTimeField(auto_now=True)),
                ('paid_amt', models.IntegerField(default=0)),
                ('complete_payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=244)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Item'),
        ),
        migrations.AddField(
            model_name='credit',
            name='userdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserData'),
        ),
    ]
