# Generated by Django 2.1 on 2019-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
