# Generated by Django 2.1 on 2019-03-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_credit_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('paid_amt', models.IntegerField(default=0)),
            ],
        ),
    ]
