# Generated by Django 2.1 on 2019-03-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
