# Generated by Django 2.1 on 2019-03-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190318_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
