# Generated by Django 2.1 on 2019-03-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_credit_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='total_amt',
            field=models.IntegerField(default=0),
        ),
    ]
